services:
  php-cli:
    image: relative/php-fpm
    container_name: relative-php-fpm
    build: .docker/php-cli
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - .docker/php-cli/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - .:/usr/src/app
